name: Build and Deploy Sphinx Docs

on: push

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies and the python package
      run: |
        pip install -r requirements.txt      
    - name: Build docs
      run: |
        cd docs  # Change to your Sphinx docs directory if not 'docs'
        make html
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: docs/build/html/    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html  # Adjust path to match where your HTML files are generated